Updates .github workflows and pixi.lock dependencies

diff --git a/.github/workflows/test-code.yaml b/.github/workflows/test-code.yaml
--- a/.github/workflows/test-code.yaml
+++ b/.github/workflows/test-code.yaml
@@ -47,6 +47,7 @@ env:
   # Set the NOTEBOOKS_DIR environment var to be the dir of Jupyter notebooks
   CI_BRANCH: ${{ github.head_ref || github.ref_name }}
   NOTEBOOKS_DIR: tutorials
+  PIXI_ENV_PREFIXES: 'py311 py312 py313'
   PIXI_DEV_ENVS: 'py311-dev py312-dev py313-dev'
   PIXI_PROD_ENVS: 'py311-prod py312-prod py313-prod'
 
@@ -141,12 +142,12 @@ jobs:
           echo "In project root run 'pixi run format-non-py' and commit changes"
 
       #- name: Force fail if any of the previous steps failed
-        #if: |
-          #steps.check_pyproject.outcome == 'failure' ||
-          #steps.check_code_linting.outcome == 'failure' ||
-          #steps.check_code_formatting.outcome == 'failure' || 
-          #steps.check_others_formatting.outcome == 'failure'
-        #run: exit 1
+      #if: |
+      #steps.check_pyproject.outcome == 'failure' ||
+      #steps.check_code_linting.outcome == 'failure' ||
+      #steps.check_code_formatting.outcome == 'failure' ||
+      #steps.check_others_formatting.outcome == 'failure'
+      #run: exit 1
 
   # Job 2: Test code and upload coverage to Codecov.
   run-tests:
@@ -216,7 +217,7 @@ jobs:
         run: |
           for env in ${{ env.PIXI_DEV_ENVS }}; do
             echo "🧪 Current env: $env"
-            pixi run -e $env build
+            pixi run build
           done
 
       - name: Upload Python package built
@@ -249,26 +250,6 @@ jobs:
           name: edl_${{ matrix.os }}_${{ runner.arch }}
           path: . # directory to extract downloaded zipped artifacts
 
-      #- name: Remove dots from python version
-      #  shell: bash
-      #  run: echo "PYVER_NODOT=${{ matrix.python-version }}" | tr -d '.' >> $GITHUB_ENV
-
-      # The local version must be higher than the PyPI version for pip to
-      # prefer the local version. So, after a new release and a new tag,
-      # remember to merge the master branch with the develop branch,
-      # and then create a new feature branch from the develop branch.
-      - name: Add local directory to pixi.toml to find the built package
-        shell: bash
-        run: |
-          echo ''
-
-
-      #echo '[feature.prod.pypi-options]' >> pixi.toml
-      #echo 'find-links = [{ path = "dist" }]' >> pixi.toml
-
-      #pixi add -f prod --pypi 'easydiffraction[dev,visualization]'
-      #pixi run pip install --find-links=dist 'easydiffraction[dev,visualization]'
-
       - name: Set up pixi
         uses: prefix-dev/setup-pixi@v0.9.0
         with:
@@ -297,7 +278,7 @@ jobs:
             echo "🧪 Current env: $env"
             pixi install -e $env
             echo "📦 Installed easydiffraction:"
-            pixi run -e $env python -m pip show easydiffraction | grep ^Version: | cut -d' ' -f2
+            pixi run -e $env python -m pip show easydiffraction | grep ^Version:
           done
 
       - name: Run unit tests (using built package from previous job)
